### ISSUE TITLE
Radial Menu Icon "Reset Fog of War" shares same definition as "Set always Invisible"

### ISSUE THREAD

**Issue by SirMotte** [SirMotte/FGU-Theme-Hearth#17]
There is no entry in the .xml and no button to be found in the graphics folders of core rpg.
![FOW](https://user-images.githubusercontent.com/82598692/117734460-ced27380-b1f3-11eb-8092-b3dcefcf81df.png)

**Comment by Gtaray** [comment]
It looks like that menu is hardcoded into Fantasy Grounds; I can't find any reference to those icons in CoreRPG. We'll likely have to request that these icons be separated.

**Comment by SirMotte** [comment]
Hardcoded for now.
